site_name: OpenFIBSEM Documentation
repo_name: DeMarcoLab/fibsem
repo_url: https://github.com/DeMarcoLab/fibsem
site_description: Documentation for the OpenFIBSEM Project
theme: 
  name: "material"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - search
  - blog:
      archive: false

nav:
  - OpenFIBSEM:
    - index.md
  - OpenFIBSEM API: 
    - openfibsem/index.md
    - Getting Started: openfibsem/getting_started.md
    - Installation: openfibsem/installation.md
    - Concepts: openfibsem/concepts.md
    - User Guide: openfibsem/user_guide.md
    - Examples: openfibsem/examples.md
    - Roadmap: openfibsem/roadmap.md
    - API Reference: openfibsem/reference.md
  - AutoLamella:
    - autolamella/index.md
    - Getting Started: autolamella/getting_started.md
    - Motivation: autolamella/motivation.md
    - User Guide: autolamella/user_guide.md
    - Machine Learning: autolamella/ml.md
    - Case Study - Serial Liftout: autolamella/case_study_serial_liftout.md
  - Blog:
    - blog/index.md